db:
  extends:
    file: docker-compose-common.yml
    service: db
  env_file:
    - config/db.dev.env

smtp:
  extends:
    file: docker-compose-common.yml
    service: smtp
  env_file:
    - config/smtp.dev.env

app:
  extends:
    file: docker-compose-common.yml
    service: app
  links:
    - db:mysql
    - smtp:smtp

web:
  extends:
    file: docker-compose-common.yml
    service: web
  links:
    - app
  volumes_from:
    - app
  env_file:
    - config/web.dev.env
