db:
  extends:
    file: docker-compose-common.yml
    service: db
  env_file:
    - config/db.prod.env

smtp:
  extends:
    file: docker-compose-common.yml
    service: smtp
  env_file:
    - config/smtp.prod.env

phpmyadmin:
  extends:
    file: docker-compose-common.yml
    service: phpmyadmin
  links:
    - db:mysql
  env_file:
    - config/phpmyadmin.prod.env

app:
  extends:
    file: docker-compose-common.yml
    service: app
  links:
    - db:mysql
    - smtp:smtp

web:
  extends:
    file: docker-compose-common.yml
    service: web
  links:
    - app
  volumes_from:
    - app
  env_file:
    - config/web.prod.env
